name: Deploy para Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir a imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/meu-app:latest .

      - name: Enviar imagem para o Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/meu-app:latest
